### ISSUE TITLE
Build in docker fails

### ISSUE THREAD

**Issue by feldim2425** [OnionIoT/source#33] opened 2022-01-11 21:43 UTC
Builds in docker fail.

I used the following commands:
```
docker run -it onion/omega2-source /bin/bash
git pull
python scripts/onion-setup-build.py -c .config.O2-minimum
make -j24
```
After a some time of compiling if failed with an error ``/root/source/include/toplevel.mk:216: recipe for target 'world' failed``.

Rerunning with ``make -j1 V=s`` gives the following output (last seemingly relevant lines):
```
SHELL= flock /root/source/tmp/.wifi-warp-core-0.1.1-1.tar.gz.flock -c '          echo "Checking out files from the git repository..."; mkdir -p /root/source/tmp/dl && cd /root/source/tmp/dl && rm -rf wifi-warp-core-0.1.1 && [ \! -d wifi-warp-core-0.1.1 ] && git clone  http://git.openwrt.org/project/iwinfo.git wifi-warp-core-0.1.1 && (cd wifi-warp-core-0.1.1 && git checkout ade8b1b299cbd5748db1acf80dd3e9f567938371 && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd wifi-warp-core-0.1.1 && git log -1 --format='\''@%ct'\''` && rm -rf wifi-warp-core-0.1.1/.git &&         tar --numeric-owner --owner=0 --group=0 --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c wifi-warp-core-0.1.1 |    gzip -nc > /root/source/tmp/dl/wifi-warp-core-0.1.1-1.tar.gz && mv /root/source/tmp/dl/wifi-warp-core-0.1.1-1.tar.gz /root/source/dl/ && rm -rf wifi-warp-core-0.1.1;     '
Checking out files from the git repository...
Cloning into 'wifi-warp-core-0.1.1'...
fatal: unable to access 'http://git.openwrt.org/project/iwinfo.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Makefile:95: recipe for target '/root/source/dl/wifi-warp-core-0.1.1-1.tar.gz' failed
make[3]: *** [/root/source/dl/wifi-warp-core-0.1.1-1.tar.gz] Error 128
make[3]: Leaving directory '/root/source/feeds/onion/wifi-warp-core'
Command exited with non-zero status 2
time: package/feeds/onion/wifi-warp-core/compile#0.04#0.04#0.36
package/Makefile:107: recipe for target 'package/feeds/onion/wifi-warp-core/compile' failed
make[2]: *** [package/feeds/onion/wifi-warp-core/compile] Error 2
make[2]: Leaving directory '/root/source'
package/Makefile:103: recipe for target '/root/source/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/root/source/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/root/source'
/root/source/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
```

The latest pulled docker image at the time of compiling had the hash ``e290b1d773bb6b67bd2d1f1910c173f17a454e97ae7d791279ebd14b21fc5fb3`` 
And the latest pulled git commit was 63c2cfec3f29ee777a0539e69b3f1854f0267552

**Comment by diabl0w** [comment] 2023-01-23 14:23
have you found a fix for this? im having the same issue

**Comment by greenbreakfast** [comment] 2023-02-22 18:00
@feldim2425 @diabl0w 

## The Problem
It looks like this was caused by outdated CA Certificates in the Docker image. Since they were outdated, they could not validate the certificates on the remote http://git.openwrt.org server.

The key error message is:
```
fatal: unable to access 'http://git.openwrt.org/project/iwinfo.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

## The Long-Term Solution - New Docker Image

We've released a new version of the [onion/omega2-source Docker image](https://hub.docker.com/r/onion/omega2-source). 
It's based on b256, the latest commit in this repo at time of writing: https://github.com/OnionIoT/source/commit/730f2344ba3264211edfcd4147664a9de5e4d349

**Please pull this latest image version** (tagged `latest` and `b256`), **launch a new container based on it, and try building again.**

## The Short-Term Solution - Keep working with your existing docker container

If you want to keep using your existing docker container, you can try updating the CA certificates in the container by running:

```
apt-get update
apt-get install --reinstall ca-certificates
```

However, we recommend using a new Docker container based on the latest image - this is the cleanest way forward.

**Closed as completed by greenbreakfast** 2023-02-22 18:00 UTC
